version: '3.7'

volumes:
  nextcloud:
  database:

services:

  proxy:
    restart: always
    image: proxy
    ports:
      - 80:80
    links:
      - nextcloud
    depends_on:
      - nextcloud
      - flexfactory

  flexfactory:
    restart: always
    image: nginx

  nextcloud:
    restart: always
    image: nextcloud
    links:
      - database
    depends_on:
      - database
    volumes:
      - nextcloud:/var/www/html

  database:
    restart: always
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=azerty
      - MYSQL_PASSWORD=azerty
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
