version: '3.7'

volumes:
  nextcloud:
    external: true
  database:
    external: true
  letsencrypt-config:
    external: true
  letsencrypt-data:
    external: true
  letsencrypt-dh:
    external: true

services:

  proxy:
    restart: always
    build: ./proxy
    ports:
      - 80:80
      - 443:443
    links:
      - nextcloud
    depends_on:
      - nextcloud
      - flexfactory
    volumes:
      - letsencrypt-data:/srv/letsencrypt
      - letsencrypt-config:/etc/letsencrypt
      - letsencrypt-dh:/etc/ssl/certs

  flexfactory:
    restart: always
    build: ./flexfactory

  nextcloud:
    restart: always
    image: nextcloud
    links:
      - database
    depends_on:
      - database
    volumes:
      - nextcloud:/var/www/html
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.tic.sh

  database:
    restart: always
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
