version: '3.7'

volumes:
  letsencrypt:
  gogs:
  matrix:

services:
  proxy:
    restart: always
    build: ./proxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - flexfactory
      - static
      - gogs
    volumes:
      - letsencrypt:/etc/letsencrypt

  flexfactory:
    restart: always
    build: ./flexfactory

  static:
    restart: always
    build: ./static

  gogs:
    restart: always
    image: gogs/gogs
    ports:
      - "2222:22"
    volumes:
      - gogs:/data

  matrix:
    restart: always
    image: matrixdotorg/synapse
    volumes:
      - matrix:/data
