version: '3.7'

services:
  proxy:
    restart: always
    build: ./proxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - flexfactory
      - static

  flexfactory:
    restart: always
    build: ./flexfactory

  static:
    restart: always
    build: ./static
