version: '3.7'

volumes:
  letsencrypt-config:
    external: true
  letsencrypt-data:
    external: true
  letsencrypt-dh:
    external: true

services:

  proxy:
    restart: always
    build: ./proxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - flexfactory
    volumes:
      - letsencrypt-data:/srv/letsencrypt
      - letsencrypt-config:/etc/letsencrypt
      - letsencrypt-dh:/etc/ssl/certs

  flexfactory:
    restart: always
    build: ./flexfactory
